# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c91b9ba5fe3a7ad605544c63145048df7da61ce7f2102d193b1ba72136d3416b5eb4b24afbc8c1667c23bb21401dce8b7da19bf7d67a6d47692422ae26f5ba1

test:
  secret_key_base: 6fbe59ac7bbe7b5eba391cb385f0bb7fdf124e340cd04417ec37603d625547083c7453ce81b32aff5f797ce3dc53a53b564b404780c8ffd5ecefb6bc10a4de64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
